### ISSUE TITLE
How to implement the Eq.(11)

### ISSUE THREAD

**Issue by yuhaoooo** [thu-ml/Prior-Guided-RGF#5]
Thanks for this excellent work. In this paper, I see the Eq.(11), which contains the vv^T term.  Because the dimensions of v is [1, 299, 299, 3]. How do you calculate the v^T and vv^T? I read the code, and find 
```Python
pert[i] = pert[i] - np.sum(pert[i] * prior) * prior / np.maximum(1e-12, np.sum(prior * prior))
```
But I cannot understant it. Could you explain this to me?
thx.

**Comment by csy530216** [comment]
Hello! I am sorry for the late reply.

Let x denote \xi_i in Eq. (11) or `pert[i]` in the code, and note that v in Eq. (11) corresponds to `prior` in the code. In fact

> (I-vv^T)x=x-vv^T x=x-(v^T x)v

and v^T x corresponds to `np.sum(pert[i] * prior)` in the code. This is the explanation.

Since in the code, both `prior` and `pert[i]` are not normalized to a unit vector with the L2 norm 1 (instead their norms are sqrt(D)), therefore the ` / np.maximum(1e-12, np.sum(prior * prior))` part is necessary.

Feel free to ask me if you have more questions.

**Comment by yuhaoooo** [comment]
Thanks for your response. I'm not familiar with the Matrix Analysis. Why ```vv^T x``` is equal to the ```(v^T x)v```?

**Comment by csy530216** [comment]
Because of the associative law of matrix multiplication, vv^T x=v(v^T x). Since (v^T x) is a scalar, v(v^T x)=(v^T x)v.

**Comment by yuhaoooo** [comment]
OK, thanks a lot for your quick reply.
